/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estrategias;

import static estrategias.Diseno.conn;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alonso
 */
public class Periodo extends javax.swing.JFrame {

    /**
     * Creates new form Periodo
     */
    static Connection conn = null;
    static Statement sta = null;
    static ResultSet res = null;
    static DefaultTableModel servidores = new DefaultTableModel();
    static int selectedRow;
    
    Estrategia es = new Estrategia("","","","","","",0,"");
    Servidor se = new Servidor("", "", "", "", "", 0);
    Periodos pe = new Periodos("",false,false,false,false,false,false,false,0,0,0);
    
    public Periodo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(44,112,213));
        
        MyTableModel dias = new MyTableModel();
        dias.addRow(new Object[]{"Lunes", false});
        dias.addRow(new Object[]{"Martes", false});
        dias.addRow(new Object[]{"Miercoles", false});
        dias.addRow(new Object[]{"Jueves", false});
        dias.addRow(new Object[]{"Viernes", false});
        dias.addRow(new Object[]{"Sabado", false});
        dias.addRow(new Object[]{"Domingo", false});
        this.Dias.setModel(dias);
        
        
    }
    
    public Periodo(Estrategia es, Periodos pe) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(44,112,213));
        
  
        this.pe = pe;
        this.es = es;
        
        MyTableModel dias = new MyTableModel();
        dias.addRow(new Object[]{"Lunes", pe.lunes});
        dias.addRow(new Object[]{"Martes", pe.martes});
        dias.addRow(new Object[]{"Miercoles", pe.miercoles});
        dias.addRow(new Object[]{"Jueves", pe.jueves});
        dias.addRow(new Object[]{"Viernes", pe.viernes});
        dias.addRow(new Object[]{"Sabado", pe.sabado});
        dias.addRow(new Object[]{"Domingo", pe.domingo});
        this.Dias.setModel(dias);
        
        TextNombreEstrategia.setText(es.nombre_estrategia);
        
        System.out.println(es.tipo_respaldo);
        System.out.println(es.modo_respaldo);
        System.out.println(es.metodo_respaldo);
        
        if(es.tipo_respaldo == "Frio") {
             Frio.setSelected(true);
        } else {
             Caliente.setSelected(true);
        }
        
        if(es.modo_respaldo == "Manual") {
             Manual.setSelected(true);
        } else {
             Automatico.setSelected(true);
        }
        
        if(es.metodo_respaldo == "Archive") {
             Archive.setSelected(true);
        } else { 
             NoArchive.setSelected(true);
        }
        
        TextNamePeriodo.setText(pe.nombre_periodo);
        Hora.setText(pe.hora+"");
        Minuto.setText(pe.minuto+"");
        Segundo.setText(pe.segundo+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoArchive = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextNamePeriodo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        Hora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Minuto = new javax.swing.JTextField();
        TextNombreEstrategia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Frio = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        Segundo = new javax.swing.JTextField();
        Caliente = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Manual = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablespaces = new javax.swing.JTable();
        Automatico = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Dias = new javax.swing.JTable();
        Archive = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();

        setTitle("Periodo");

        NoArchive.setForeground(new java.awt.Color(255, 255, 255));
        NoArchive.setText("No Archive");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Objetos: ");

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Todos");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Periodicidad de Respaldos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre de periodo: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Planeacion por Dias:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha de Inicio:");

        Hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hora.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estrategia");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hora");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de estrategia: ");

        Minuto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Minuto.setText("0");

        TextNombreEstrategia.setEditable(false);
        TextNombreEstrategia.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Minutos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de respaldo: ");

        Frio.setForeground(new java.awt.Color(255, 255, 255));
        Frio.setText("Frio");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Segundos");

        Segundo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Segundo.setText("0");

        Caliente.setForeground(new java.awt.Color(255, 255, 255));
        Caliente.setText("Caliente");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modo de respaldo: ");

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Manual.setForeground(new java.awt.Color(255, 255, 255));
        Manual.setText("Manual");

        Tablespaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tablespace", "Prioridad"
            }
        ));
        jScrollPane2.setViewportView(Tablespaces);

        Automatico.setForeground(new java.awt.Color(255, 255, 255));
        Automatico.setText("Automatico");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Metodo de respaldo: ");

        Dias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Dia", "Seleccion"
            }
        ));
        jScrollPane3.setViewportView(Dias);

        Archive.setForeground(new java.awt.Color(255, 255, 255));
        Archive.setText("Archive");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Horario: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextNombreEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Manual)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Automatico))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(Frio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Caliente))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Archive)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NoArchive)))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox1))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(TextNamePeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(149, 149, 149)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel11))
                                                        .addGap(5, 5, 5)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel12)
                                                            .addComponent(Minuto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel13)
                                                            .addComponent(Segundo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel14))
                                                .addGap(74, 74, 74))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextNombreEstrategia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Frio)
                            .addComponent(Caliente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Manual)
                            .addComponent(jLabel4)
                            .addComponent(Automatico))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Archive)
                            .addComponent(NoArchive)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(3, 3, 3)
                                .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Minuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Segundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextNamePeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            //Eliminar primero
             conn = Dao.Enlace(conn);
             Dao.elimnarEstrategia(TextNombreEstrategia.getText());
            //Crear------------
            String tipo = Frio.isSelected() ? Frio.getText() : Caliente.getText();
            String modo = Manual.isSelected() ? Manual.getText() : Automatico.getText();
            String metodo = Archive.isSelected() ? Archive.getText() : NoArchive.getText();
            String objetos = "";
            for (int i = 0; i < Tablespaces.getRowCount(); i++) {
                if ("true".equals(Tablespaces.getValueAt(i, 1).toString())) {
                    objetos += Tablespaces.getValueAt(i, 0).toString() + ",";
                }
            }

           

            Periodos pe = new Periodos(TextNamePeriodo.getText(), false, false, false, false, false, false, false, 0, 0, 0);
            Dao.insertPeriodo(pe);

            Estrategia es = new Estrategia(TextNombreEstrategia.getText(), tipo, modo, metodo, objetos, TextNamePeriodo.getText(), 0, se.nombre_servidor);
            Dao.insertEstrategia(es);

            GuardarArchivosBat(); // Crea los rcv y bat
            GuardarArchivosRCV(es); // Crea los rcv y bat
            Timestamp s = new Timestamp(System.currentTimeMillis());
            if ("Automatico".equals(modo)) {
                Dao.createJob2(es.nombre_estrategia, "C:\\Users\\alonso\\Desktop\\Estrategia\\Estrategias\\rman\\ES9S.bat", "BYHOUR=4;BYMINUTE=1", s);
            }

            conn.close();

            JOptionPane.showMessageDialog(null, "La estrategia se ha actualizado correctamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        for(int i=0; i< this.Tablespaces.getRowCount(); i++) {
           this.Tablespaces.setValueAt(true, i, 1);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Periodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Periodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Periodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Periodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Periodo().setVisible(true);
            }
        });
    }
    
    public class MyTableModel extends DefaultTableModel {

    public MyTableModel() {
      super(new String[]{"Tablespace_name", "Check"}, 0);
    }

    @Override
    public Class<?> getColumnClass(int columnIndex) {
      Class clazz = String.class;
      switch (columnIndex) {
        case 0:
          clazz = String.class;
          break;
        case 1:
          clazz = Boolean.class;
          break;
      }
      return clazz;
    }

    @Override
    public boolean isCellEditable(int row, int column) {
      return column == 1;
    }

    @Override
    public void setValueAt(Object aValue, int row, int column) {
      if (aValue instanceof Boolean && column == 1) {
        System.out.println(aValue);
        Vector rowData = (Vector)getDataVector().get(row);
        rowData.set(1, (boolean)aValue);
        fireTableCellUpdated(row, column);
      }
    }

  }
 public void GuardarArchivosBat() {
        try {
            // Escritura del archivo BAT
            String texto = "set ORACLE_HOME=C:\\Oracle\\product\\11.2.0\\server\n"
                    + "set ORACLE_SID=XE \n"
                    + "set NLS_DATE_FORMAT=\"YYYY-MON-DD HH24:MI:SS\"\n"
                    + "\n"
                    + "%ORACLE_HOME%\\bin\\rman target / log = ./logs/" + TextNombreEstrategia.getText() + ".log cmdfile ./rman/" + TextNombreEstrategia.getText() + ".rcv\n"
                    + "\n"
                    + "exit 0";
            FileWriter lector = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".bat");
            BufferedWriter contenido = new BufferedWriter(lector);
            contenido.write(texto);
            contenido.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void GuardarArchivosRCV(Estrategia es) {
        if ("Frio".equals(es.tipo_respaldo)) {
            if ("Archive".equals(es.modo_respaldo)) {
                if (jCheckBox1.isSelected()) {
                    try {
                        // Escritura del archivo RCV
                        String texto2 = "connect target sys/root@\"+this.se.ip+\";\n"
                                + "shutdown\n"
                                + "startup mount\n"
                                + "spool log to \"./logs/MyLog.log\"\n"
                                + "BACKUP DATABASE SPFILE PLUS ARCHIVELOG;\n"
                                + "alter database open resetlogs;\n"
                                + "spool log off";
                        FileWriter lector2 = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".rcv");
                        BufferedWriter contenido2 = new BufferedWriter(lector2);
                        contenido2.write(texto2);
                        contenido2.close();

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    try {
                        String contenido = "";
                        for (int i = 0; i < this.Tablespaces.getRowCount(); i++) {
                            if ("true".equals(Tablespaces.getValueAt(i, 1).toString())) {
                                contenido += "BACKUP TABLESPACE" + Tablespaces.getValueAt(i, 0).toString() + "PLUS ARCHIVELOG; \n";
                            }
                        }
                        if ("".equals(contenido)) {
                            String texto = "connect target sys/root@\"+this.se.ip+\";\n"
                                    + "shutdown\n"
                                    + "startup mount\n"
                                    + "spool log to \"./logs/MyLog.log\"\n"
                                    + contenido
                                    + "alter database open resetlogs;\n"
                                    + "spool log off";

                            FileWriter lector2 = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".rcv");
                            BufferedWriter contenido2 = new BufferedWriter(lector2);
                            contenido2.write(texto);
                            contenido2.close();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
            if ("No Archive".equals(es.modo_respaldo)) {
                if (jCheckBox1.isSelected()) {
                    try {

                        // Escritura del archivo RCV
                        String texto2 = "connect target sys/root@\"+this.se.ip+\";\n"
                                + "shutdown\n"
                                + "startup mount\n"
                                + "spool log to \"./logs/MyLog.log\"\n"
                                + "BACKUP DATABASE;\n"
                                + "alter database open resetlogs;\n"
                                + "spool log off";
                        FileWriter lector2 = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".rcv");
                        BufferedWriter contenido2 = new BufferedWriter(lector2);
                        contenido2.write(texto2);
                        contenido2.close();

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    try {
                        String contenido = "";
                        for (int i = 0; i < this.Tablespaces.getRowCount(); i++) {
                            if ("true".equals(Tablespaces.getValueAt(i, 1).toString())) {
                                contenido += "BACKUP TABLESPACE" + Tablespaces.getValueAt(i, 0).toString() + "PLUS ARCHIVELOG; \n";
                            }
                        }
                        if ("".equals(contenido)) {
                            String texto = "connect target sys/root@\"+this.se.ip+\";\n"
                                    + "shutdown\n"
                                    + "startup mount\n"
                                    + "spool log to \"./logs/MyLog.log\"\n"
                                    + contenido
                                    + "alter database open resetlogs;\n"
                                    + "spool log off";

                            FileWriter lector2 = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".rcv");
                            BufferedWriter contenido2 = new BufferedWriter(lector2);
                            contenido2.write(texto);
                            contenido2.close();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
        if ("Caliente".equals(es.tipo_respaldo)) {
            if ("Archive".equals(es.modo_respaldo)) {
                if (jCheckBox1.isSelected()) {
                    try {

                        // Escritura del archivo RCV
                        String texto2 = "connect target sys/root@\"+this.se.ip+\";\n"
                                + "spool log to \"./logs/MyLog.log\"\n"
                                + "BACKUP DATABASE SPFILE PLUS ARCHIVELOG;\n"
                                + "spool log off";
                        FileWriter lector2 = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".rcv");
                        BufferedWriter contenido2 = new BufferedWriter(lector2);
                        contenido2.write(texto2);
                        contenido2.close();

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    try {
                        String contenido = "";
                        for (int i = 0; i < this.Tablespaces.getRowCount(); i++) {
                            if ("true".equals(Tablespaces.getValueAt(i, 1).toString())) {
                                contenido += "BACKUP TABLESPACE" + Tablespaces.getValueAt(i, 0).toString() + "PLUS ARCHIVELOG; \n";
                            }
                        }
                        if ("".equals(contenido)) {
                            String texto = "connect target sys/root@\"+this.se.ip+\";\n"
                                    + "spool log to \"./logs/MyLog.log\"\n"
                                    + contenido
                                    + "spool log off";

                            FileWriter lector2 = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".rcv");
                            BufferedWriter contenido2 = new BufferedWriter(lector2);
                            contenido2.write(texto);
                            contenido2.close();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
            if ("No Archive".equals(es.modo_respaldo)) {
                if (jCheckBox1.isSelected()) {
                    try {

                        // Escritura del archivo RCV
                        String texto2 = "connect target sys/root@\"+this.se.ip+\";\n"
                                + "spool log to \"./logs/MyLog.log\"\n"
                                + "BACKUP DATABASE;\n"
                                + "spool log off";
                        FileWriter lector2 = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".rcv");
                        BufferedWriter contenido2 = new BufferedWriter(lector2);
                        contenido2.write(texto2);
                        contenido2.close();

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    try {
                        String contenido = "";
                        for (int i = 0; i < this.Tablespaces.getRowCount(); i++) {
                            if ("true".equals(Tablespaces.getValueAt(i, 1).toString())) {
                                contenido += "BACKUP TABLESPACE" + Tablespaces.getValueAt(i, 0).toString() + "PLUS ARCHIVELOG; \n";
                            }
                        }
                        if ("".equals(contenido)) {
                            String texto = "connect target sys/root@\"+this.se.ip+\";\n"
                                    + "spool log to \"./logs/MyLog.log\"\n"
                                    + contenido
                                    + "spool log off";

                            FileWriter lector2 = new FileWriter("./rman/" + TextNombreEstrategia.getText() + ".rcv");
                            BufferedWriter contenido2 = new BufferedWriter(lector2);
                            contenido2.write(texto);
                            contenido2.close();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Archive;
    private javax.swing.JRadioButton Automatico;
    private javax.swing.JRadioButton Caliente;
    private javax.swing.JTable Dias;
    private javax.swing.JRadioButton Frio;
    private javax.swing.JTextField Hora;
    private javax.swing.JRadioButton Manual;
    private javax.swing.JTextField Minuto;
    private javax.swing.JRadioButton NoArchive;
    private javax.swing.JTextField Segundo;
    private javax.swing.JTable Tablespaces;
    private javax.swing.JTextField TextNamePeriodo;
    private javax.swing.JTextField TextNombreEstrategia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
